### PR TITLE
after git push, system appears that still erasing files

### PR DESCRIPTION
**Pull request by sergiomb2**
Hi, 
you got 3 distinct commits , you may merge each one separately  .

### CODE REVIEW

**Comment by sergiomb2** [comment]
First commit , just show error when they happened , if no errors output won't change

**Comment by sergiomb2** [comment]
Latest commits is for https://github.com/gabrys/svn2github/issues/7 , I'm testing now

**Comment by milahu** [comment]
> Why not use XZ compressed data

because the difference is almost zero (15%)

```
cd ~/src/svn2github/cache/
tarfile=cache.milahu.appwork-utils.tar
xz -k $tarfile
gzip -k $tarfile
du -sh *
46M     cache.milahu.appwork-utils.tar
42M     cache.milahu.appwork-utils.tar.gz
40M     cache.milahu.appwork-utils.tar.xz
```

**Comment by sergiomb2** [comment]
https://unix.stackexchange.com/questions/108100/why-are-tar-archive-formats-switching-to-xz-compression-to-replace-bzip2-and-wha

BTW in https://github.com/sergiomb2/svn2github you have my devel , unfortunately is not finished yet and is not much functional at first run , but I going close this PR to stop send notifications on every modification that I do in my repo 

Best regards

**Pull request closed without merging**
